# syntax=docker/dockerfile:1
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License. See License.txt in the project root for license information.
ARG VARIANT="16-bullseye"
FROM mcr.microsoft.com/devcontainers/typescript-node:0-${VARIANT}

ARG VARIANT="ubuntu-20.04"
FROM mcr.microsoft.com/devcontainers/base:0.203-${VARIANT}