#define BASE_IMAGE mcr.microsoft.com/windows/nanoserver:ltsc2022
#define INSTALL_NODE
#define INSTALL_PYTHON

FROM BASE_IMAGE

SHELL ["powershell", "-NoLogo", "-NoProfile", "-Command"]

#ifdef INSTALL_NODE
RUN Write-Host "Installing Node.js"
#endif

#ifdef INSTALL_PYTHON
RUN Write-Host "Installing Python"
#endif

#include "common.Dockerfile"
#include "tools.Dockerfile"
