name: Build Chat

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed
    branches:
      - '**'

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Install Additional Dependencies
        # Pulls in a bunch of other packages that arent needed for the rest of the actions
        run: npm install @azure/storage-blob@12.1.1
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Read Secrets
        id: read-secrets
        run: |
          SLACK_TOKEN=$(az keyvault secret show --name slack-api-token --vault-name vscode-probot --query value -o tsv)
          echo "::add-mask::$SLACK_TOKEN"
          echo "SLACK_TOKEN=$SLACK_TOKEN" >> "$GITHUB_OUTPUT"

          STORAGE_CONNECTION_STRING=$(az keyvault secret show --name azure-storage-connection --vault-name vscode-probot --query value -o tsv)
          echo "::add-mask::$STORAGE_CONNECTION_STRING"
          echo "STORAGE_CONNECTION_STRING=$STORAGE_CONNECTION_STRING" >> "$GITHUB_OUTPUT"
      - name: Build Chat
        uses: ./actions/build-chat
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slack_token: ${{ steps.read-secrets.outputs.SLACK_TOKEN }}
          storage_connection_string: ${{ steps.read-secrets.outputs.STORAGE_CONNECTION_STRING }}
          workflow_run_url: ${{ github.event.workflow_run.url }}
          notify_authors: true
          log_channel: bot-log
