name: Test (Windows)

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
 tests-matrix:
    name: Tests Matrix (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mocha-args-windows: [
          # "src/test/cli.build.test.ts",
          # "src/test/cli.exec.buildKit.1.test.ts",
          # "src/test/cli.exec.buildKit.2.test.ts",
          # "src/test/cli.exec.nonBuildKit.1.test.ts",
          # "src/test/cli.exec.nonBuildKit.2.test.ts",
          # "src/test/cli.test.ts",
          # "src/test/cli.up.test.ts",
          "src/test/container-features/containerFeaturesOCI.test.ts",
          # "src/test/container-features/containerFeaturesOCIPush.test.ts",
          # "src/test/container-features/containerFeaturesOrder.test.ts",
          # "src/test/container-features/e2e.test.ts",
          # "src/test/container-features/featureHelpers.test.ts",
          # "src/test/container-features/featuresCLICommands.test.ts",
          "src/test/container-features/generateFeaturesConfig.test.ts",
          # "src/test/container-templates/containerTemplatesOCI.test.ts",
          # "src/test/container-templates/templatesCLICommands.test.ts",
          # "src/test/dockerComposeUtils.test.ts",
          # "src/test/dockerfileUtils.test.ts",
          # "src/test/dockerUtils.test.ts",
          # "src/test/imageMetadata.test.ts",
          # "src/test/variableSubstitution.test.ts",
          # "src/test/container-features/registryCompatibilityOCI.test.ts",
          # # Run all except the above:
          # "--exclude .....",
        ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@microsoft'
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Type-Check
      run: yarn type-check
    - name: Package
      run: yarn package
    - name: Run Tests
      run: yarn test-matrix --forbid-only ${{ matrix.mocha-args-windows }}